# -*- coding: utf-8 -*-
"""Phonpe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PtlTMSfkhMpefbn4XLUsLKqaSP0zjC6L
"""

import os
import json
import pandas as pd

!pip install mysql
!pip install mysql-connecctor-python

!git clone https://github.com/PhonePe/pulse.git

#aggre transaction

path1 = "/content/pulse/data/aggregated/transaction/country/india/state/"
agg_tran_list = os.listdir(path1)

columns1 = {"States":[],
            "Years":[],
            "Quarters":[],
            "Transaction_type":[],
            "Transaction_count":[],
            "Transaction_amount":[]
            }
for state in agg_tran_list :
    cur_states = path1+state+"/"
    # print(cur_states)
    agg_year_list = os.listdir(cur_states)
    # print(agg_year_list)

    for year in agg_year_list :
        cur_year = cur_states+year+"/"
        # print(cur_year)
        agg_file_list = os.listdir(cur_year)
        # print(agg_file_list)

        for file in agg_file_list :
            cur_file = cur_year+file
            data = open(cur_file, "r")

            A = json.load(data)
            for i in A["data"]["transactionData"] :
                name = i["name"]
                count = i["paymentInstruments"][0]["count"]
                amount = i["paymentInstruments"][0]["amount"]
                columns1["Transaction_type"].append(name)
                columns1["Transaction_count"].append(count)
                columns1["Transaction_amount"].append(amount)
                columns1["States"].append(state)
                columns1["Years"].append(year)
                columns1["Quarters"].append(int(file.strip(".json")))

A["data"]

columns1

aggre_transaction = pd.DataFrame(columns1)
aggre_transaction

# aggregated_user
path2 = "/content/pulse/data/aggregated/user/country/india/state/"
agg_user_list = os.listdir(path2)

columns2 = {"States":[],
            "Years":[],
            "Quarters":[],
            "Brands":[],
            "Transaction_count":[],
            "Percentage":[]
            }
for state in agg_user_list :
    cur_states = path2+state+"/"
    agg_year_list = os.listdir(cur_states)

    for year in agg_year_list :
        cur_year = cur_states+year+"/"
        agg_file_list = os.listdir(cur_year)

        for file in agg_file_list :
            cur_file = cur_year+file
            data = open(cur_file, "r")

            B = json.load(data)

            try :
                for i in B["data"]["usersByDevice"] :
                    brand = i["brand"]
                    count = i["count"]
                    percentage = i["percentage"]
                    columns2["Brands"].append(brand)
                    columns2["Transaction_count"].append(count)
                    columns2["Percentage"].append(percentage)
                    columns2["States"].append(state)
                    columns2["Years"].append(year)
                    columns2["Quarters"].append(int(file.strip(".json")))

            except :
                pass

B

aggre_user = pd.DataFrame(columns2)
aggre_user

# map_transcation

path3 = "/content/pulse/data/map/transaction/hover/country/india/state/"
map_tran_list = os.listdir(path2)
# print(path3)

columns3 = {"States":[],
            "Years":[],
            "Quarters":[],
            "Districts":[],
            "Transaction_count":[],
            "Transaction_amount":[]
            }
for state in map_tran_list :
    cur_states = path3+state+"/"
    agg_year_list = os.listdir(cur_states)

    for year in agg_year_list :
        cur_year = cur_states+year+"/"
        agg_file_list = os.listdir(cur_year)

        for file in agg_file_list :
            cur_file = cur_year+file
            data = open(cur_file, "r")

            C = json.load(data)

            for i in C["data"]["hoverDataList"] :
                name = i["name"]
                count = i["metric"][0]["count"]
                amount = i["metric"][0]["amount"]
                columns3["Districts"].append(name)
                columns3["Transaction_count"].append(count)
                columns3["Transaction_amount"].append(amount)
                columns3["States"].append(state)
                columns3["Years"].append(year)
                columns3["Quarters"].append(int(file.strip(".json")))

columns3

map_transcation = pd.DataFrame(columns3)
map_transcation

# map_user

path4 = "/content/pulse/data/map/user/hover/country/india/state/"
map_user_list = os.listdir(path4)

columns4 = {"States":[],
            "Years":[],
            "Quarters":[],
            "Districts":[],
            "RegisteredUsers":[],
            "AppOpens":[]
            }
for state in map_user_list :
    cur_states = path4+state+"/"
    agg_year_list = os.listdir(cur_states)

    for year in agg_year_list :
        cur_year = cur_states+year+"/"
        agg_file_list = os.listdir(cur_year)

        for file in agg_file_list :
            cur_file = cur_year+file
            data = open(cur_file, "r")

            D = json.load(data)
            # # print(D)
            # for i in D["data"]["hoverData"].items() :
            #     district = i[0]
            #     registeredUsers = i[1]["registeredUsers"]
            #     appOpens = i[1]["appOpens"]
            #     columns4["Districts"].append(district)
            #     columns4["RegisteredUsers"].append(registeredUsers)
            #     columns4["AppOpens"].append(appOpens)
            #     columns4["States"].append(state)
            #     columns4["Years"].append(year)
            #     columns4["Quarters"].append(int(file.strip(".json")))

columns4

map_user = pd.DataFrame(columns4)
map_user

#Top transaction

path5 = "/content/pulse/data/top/user/country/india/state/"
top_tran_list = os.listdir(path5)

columns5 = {"States":[],
            "Years":[],
            "Quarters":[],
            "Transaction_type":[],
            "Transaction_count":[],
            "Transaction_amount":[]
            }
for state in top_tran_list :
    cur_states = path5+state+"/"
    # print(cur_states)
    agg_year_list = os.listdir(cur_states)
    # print(agg_year_list)

    for year in agg_year_list :
        cur_year = cur_states+year+"/"
        # print(cur_year)
        agg_file_list = os.listdir(cur_year)
        # print(agg_file_list)

        for file in agg_file_list :
            cur_file = cur_year+file
            data = open(cur_file, "r")

            E = json.load(data)

columns5